### ISSUE TITLE
Support WebGPU backend as well as Webgl2

### ISSUE THREAD

**Issue by Oberdiah** [happy-turtle/cross-platform-renderer#1]
First off thank you for creating this example, it's been invaluable in helping me understand how to get a cross-platform project off the ground

Is it possible to add WebGPU backend support? Currently if you attempt to use any wgpu features it crashes because Webgl2 doesn't support them.

**Comment by happy-turtle** [comment]
I'm glad it helps! That is why I'm sharing this.

You need to change the [device limits](https://docs.rs/wgpu/latest/wgpu/struct.Limits.html) in the `DeviceDescriptor` to  `downlevel_defaults()` or `default()`.

If you like you can create a pull request and add the instructions to the readme.

**Comment by Oberdiah** [comment]
Unfortunately, it doesn't appear to be that easy - even on Chrome Canary with [#enable-unsafe-webgpu](chrome://flags/#enable-unsafe-webgpu) I still get the error "Limit 'max_compute_workgroups_per_dimension' value 65535 is better than allowed 0" if I make that change.

Happy to create a pull request once I figure out how to do it, though

**Comment by happy-turtle** [comment]
Is it running on WebGPU? You could try to change `let​ instance ​=​ wgpu​::​Instance​::​new​(wgpu​::​Backends​::​all​());` to `wgpu::Backends::PRIMARY` to exclude WebGL, see [here](https://docs.rs/wgpu/latest/wgpu/struct.Backends.html). Other than that I am out of ideas. I need to try it myself, that might take me a few days though.

**Comment by Oberdiah** [comment]
Changing the backend to `wgpu::Backends::PRIMARY` causes `instance.request_adapter(...)` to fail and return `None`, which suggests that the WebGPU backend is just completely unavailable for some reason.

I can run samples such as https://austin-eng.com/webgpu-samples/samples/computeBoids fine, though, so the browser is clearly capable in some respects.

I'll do some more digging and maybe ask on the wgpu Matrix, there's probably something obvious I'm missing but I just can't see it

Edit: Upon further digging, you also need to disable the "webgl" feature under `dependencies.wgpu` in core/Cargo.toml, and set the `--cfg=web_sys_unstable_apis` rust flag. Now it fails because the `instance.request_adapter(...).await()` call is asynchronous (see [here](https://github.com/gfx-rs/wgpu/issues/2197#issuecomment-974909987)) rather than webgpu itself not being enabled, which I suppose is a step forward. Will investigate further.

**Comment by happy-turtle** [comment]
Oh yes, I forgot about the webgl feature flag, good point.

Can you just block on `request_adapter()`? Just like I did with the whole `run()` function. Maybe something like `pollster::block_on(instance.request_adapter(...).await)`, so that it does not return a future?

**Comment by Oberdiah** [comment]
Unfortunately not - however, the wasm-bindgen-futures crate appears designed pretty much exactly for this use-case, so calling `lib.rs::run()` from within its `spawn_local` does finally work correctly

**Comment by Oberdiah** [comment]
Closing issue as [changes have now been merged](https://github.com/happy-turtle/cross-platform-renderer/pull/2)
